Imports System.ComponentModel
Imports System.Text
Imports System.IO
Imports DevExpress.XtraBars.Docking


Partial Public Class Form1
    Shared Sub New()
        DevExpress.UserSkins.BonusSkins.Register()
        DevExpress.Skins.SkinManager.EnableFormSkins()
    End Sub
    Public Sub New()
        InitializeComponent()
        ' This line of code is generated by Data Source Configuration Wizard
        CentrosTableAdapter1.Fill(EjemploPivotGridDataSet1.Centros)
        ' This line of code is generated by Data Source Configuration Wizard
        ' Fill a ExcelDataSource
        ExcelDataSource1.Fill()
        ' This line of code is generated by Data Source Configuration Wizard
        GeneralTableAdapter1.Fill(EjemploPivotGridDataSet11.General)
    End Sub


    Private ruta As String = "C:\Users\mterzolo\Documents\Visual Studio 2013\Projects\Workspaces\Workspaces\ws\"
    Private db As New EspaciosDataSet
    Private controles As New List(Of String)

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load

        cargarnombresdecontroles()

        Dim ta As New EspaciosDataSetTableAdapters.espTableAdapter
        ta.Fill(db.esp)

        Dim nombre As String
        Dim fila As EspaciosDataSet.espRow

        For Each fila In db.esp.Rows
            nombre = Trim(fila.Nombre)
            ComboBox1.Items.Add(nombre)
            WorkspaceManager1.LoadWorkspace(nombre, StringToStream(fila.layout, System.Text.Encoding.UTF8))

        Next

        'WorkspaceManager1.LoadWorkspace("ultimo", ruta & "wsultimo.xml")
        'WorkspaceManager1.ApplyWorkspace("ultimo")
        'WorkspaceManager1.RemoveWorkspace("ultimo")

    End Sub

    Public Shared Function StringToStream(input As String, enc As Encoding) As Stream
        Dim memoryStream = New MemoryStream()
        Dim streamWriter = New StreamWriter(memoryStream, enc)
        streamWriter.Write(input)
        streamWriter.Flush()
        memoryStream.Position = 0
        Return memoryStream
    End Function

    Private Sub Form1_FormClosing(sender As Object, e As FormClosingEventArgs) Handles MyBase.FormClosing
        WorkspaceManager1.SaveWorkspace("ultimo", ruta & "wsultimo.xml", True)
    End Sub

    Private Sub ComboBox1_SelectedIndexChanged(sender As Object, e As EventArgs) Handles ComboBox1.SelectedIndexChanged
        Dim nombre As String = ComboBox1.SelectedItem.ToString
        WorkspaceManager1.ApplyWorkspace(nombre)
        For Each row In Me.db.esp.ToList
            If row.Nombre = nombre Then
                controlarcontrolesfaltantes(row.layout)
            End If
        Next
    End Sub

    Private Sub SimpleButton2_Click_1(sender As Object, e As EventArgs) Handles SimpleButton2.Click
        Dim nombre As String = InputBox("Ingrese el nombre del espacio de trabajo", "Grabar un Espacio de Trabajo")

        If Not nombre = "" Then
            WorkspaceManager1.SaveWorkspace(nombre, ruta & nombre & ".xml", True)
            grabarenbase(nombre)
            borrararchivo(nombre)
            ComboBox1.Items.Add(nombre)
        End If

    End Sub

    Private Sub grabarenbase(ByVal nombre As String)
        Dim texto As String = leertexto(ruta & nombre & ".xml")
        If Not Text Is "" Then
            Dim fila As EspaciosDataSet.espRow = db.esp.NewespRow
            fila.Nombre = nombre
            fila.layout = texto
            db.esp.AddespRow(fila)
            Dim ta As New EspaciosDataSetTableAdapters.espTableAdapter
            ta.Update(db.esp)
        End If

    End Sub

    Private Sub borrararchivo(ByVal nombre As String)

        Dim archivo As String
        archivo = ruta & nombre & ".xml"
        If System.IO.File.Exists(archivo) = True Then
            System.IO.File.Delete(archivo)
        End If
    End Sub

    Private Function leertexto(ByVal archivo As String) As String
        Try
            Using sr As New StreamReader(archivo)
                Return sr.ReadToEnd()
            End Using
        Catch e As Exception
            Return ""
        End Try
    End Function

    Private Sub cargarnombresdecontroles()
        For Each c As Control In Me.Controls(0).Controls
            If Not c.Name = "" Then
                controles.Add(c.Name)
                'Debug.WriteLine(c.GetType().ToString)
            End If
        Next
    End Sub

    Private Sub SimpleButton1_Click(sender As Object, e As EventArgs) Handles SimpleButton1.Click
        If Not Me.ComboBox1.SelectedIndex = -1 Then
            Dim rta As Integer = MsgBox("¿Realmente quiere borrar " & Me.ComboBox1.SelectedItem.ToString & "?", MsgBoxStyle.YesNo)
            If rta = vbYes Then
                borrarregistro(Me.ComboBox1.SelectedItem.ToString)
                Me.ComboBox1.Items.Remove(ComboBox1.SelectedItem)
            End If
        End If

    End Sub

    Private Sub borrarregistro(ByVal nombre As String)

        For Each row In Me.db.esp.ToList

            If row.Nombre = nombre Then
                row.Delete()
            End If

        Next

        Dim ta As New EspaciosDataSetTableAdapters.espTableAdapter
        ta.Update(db.esp)

    End Sub

    Private Sub controlarcontrolesfaltantes(ByVal xml As String)
        For Each nombre In controles
            If Not xml.Contains(nombre) Then
                Dim rta As Integer = MsgBox("El control " & nombre & " no se encuentra contemplado en el espacio de trabajo seleccionado. ¿Mostrar?",
                                            MsgBoxStyle.YesNo)
                If rta = vbYes Then
                    Me.Controls(0).Controls(nombre).Visible = True
                End If
            End If
        Next
    End Sub

    Private Sub SimpleButton3_Click(sender As Object, e As EventArgs) Handles SimpleButton3.Click
        While DockManager1.HiddenPanels.Count > 0
            DockManager1.HiddenPanels(0).Visibility = DockVisibility.Visible
        End While
    End Sub
End Class
